config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zsh_alias:
    src: zsh_alias
    dst: ~/.zsh_alias
  f_clang-format_c:
    src: clang-format_c
    dst: ~/.clang-format_c
  f_clang-format_cpp:
    src: clang-format_cpp
    dst: ~/.clang-format_cpp
  f_clang-tidy:
    src: clang-tidy
    dst: ~/.clang-tidy
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_config_dunst_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_config_dunst_reload.sh:
    src: config/dunst/reload.sh
    dst: ~/.config/dunst/reload.sh
    chmod: '744'
  f_config_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_config_i3_scripts_soundboard.sh:
    src: config/i3/scripts/soundboard.sh
    dst: ~/.config/i3/scripts/soundboard.sh
    chmod: '744'
  f_config_i3_scripts_keyboard_switcher.sh:
    src: config/i3/scripts/keyboard_switcher.sh
    dst: ~/.config/i3/scripts/keyboard_switcher.sh
    chmod: '744'
  f_config_i3_scripts_lock.sh:
    src: config/i3/scripts/lock.sh
    dst: ~/.config/i3/scripts/lock.sh
    chmod: '744'
  f_config_i3_scripts_set_wallpaper.sh:
    src: config/i3/scripts/set_wallpaper.sh
    dst: ~/.config/i3/scripts/set_wallpaper.sh
    chmod: '744'
  f_config_i3_scripts_suspend.sh:
    src: config/i3/scripts/suspend.sh
    dst: ~/.config/i3/scripts/suspend.sh
    chmod: '744'
  f_config_i3_wallpapers_krapaince_avatar.png:
    src: config/i3/wallpapers/Krapaince/avatar.png
    dst: ~/.config/i3/wallpapers/Krapaince/avatar.png
  f_config_i3_wallpapers_krapaince-master_avatar.png:
    src: config/i3/wallpapers/Krapaince-MASTER/avatar.png
    dst: ~/.config/i3/wallpapers/Krapaince-MASTER/avatar.png
  f_config_kitty_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_config_nvim_coc_snippets_c.json:
    src: config/nvim/coc/snippets/c.json
    dst: ~/.config/nvim/coc/snippets/c.json
  f_config_nvim_coc_snippets_cpp.json:
    src: config/nvim/coc/snippets/cpp.json
    dst: ~/.config/nvim/coc/snippets/cpp.json
  f_config_nvim_general_settings.vim:
    src: config/nvim/general/settings.vim
    dst: ~/.config/nvim/general/settings.vim
  f_config_nvim_keys_mappings.vim:
    src: config/nvim/keys/mappings.vim
    dst: ~/.config/nvim/keys/mappings.vim
  f_config_nvim_lua_plug-colorizer.lua:
    src: config/nvim/lua/plug-colorizer.lua
    dst: ~/.config/nvim/lua/plug-colorizer.lua
  f_config_nvim_plug-config_airline.vim:
    src: config/nvim/plug-config/airline.vim
    dst: ~/.config/nvim/plug-config/airline.vim
  f_config_nvim_plug-config_coc.vim:
    src: config/nvim/plug-config/coc.vim
    dst: ~/.config/nvim/plug-config/coc.vim
  f_config_nvim_plug-config_fzf.vim:
    src: config/nvim/plug-config/fzf.vim
    dst: ~/.config/nvim/plug-config/fzf.vim
  f_config_nvim_plug-config_git-messenger.vim:
    src: config/nvim/plug-config/git-messenger.vim
    dst: ~/.config/nvim/plug-config/git-messenger.vim
  f_config_nvim_plug-config_markdown-preview.vim:
    src: config/nvim/plug-config/markdown-preview.vim
    dst: ~/.config/nvim/plug-config/markdown-preview.vim
  f_config_nvim_plug-config_nerdtree.vim:
    src: config/nvim/plug-config/nerdtree.vim
    dst: ~/.config/nvim/plug-config/nerdtree.vim
  f_config_nvim_plug-config_rnvimr.vim:
    src: config/nvim/plug-config/rnvimr.vim
    dst: ~/.config/nvim/plug-config/rnvimr.vim
  f_config_nvim_plug-config_vim-clang-format.vim:
    src: config/nvim/plug-config/vim-clang-format.vim
    dst: ~/.config/nvim/plug-config/vim-clang-format.vim
  f_config_nvim_plug-config_vim-commentary.vim:
    src: config/nvim/plug-config/vim-commentary.vim
    dst: ~/.config/nvim/plug-config/vim-commentary.vim
  f_config_nvim_plug-config_vim-cpp-enhanced-highlight.vim:
    src: config/nvim/plug-config/vim-cpp-enhanced-highlight.vim
    dst: ~/.config/nvim/plug-config/vim-cpp-enhanced-highlight.vim
  f_config_nvim_plug-config_vim-illuminate.vim:
    src: config/nvim/plug-config/vim-illuminate.vim
    dst: ~/.config/nvim/plug-config/vim-illuminate.vim
  f_config_nvim_plug-config_vista.vim:
    src: config/nvim/plug-config/vista.vim
    dst: ~/.config/nvim/plug-config/vista.vim
  f_config_nvim_vim-plug_plugins.vim:
    src: config/nvim/vim-plug/plugins.vim
    dst: ~/.config/nvim/vim-plug/plugins.vim
  f_config_nvim_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  f_config_nvim_github-markdown.css:
    src: config/nvim/github-markdown.css
    dst: ~/.config/nvim/github-markdown.css
  f_config_nvim_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_config_nvim_snippet.vim:
    src: config/nvim/snippet.vim
    dst: ~/.config/nvim/snippet.vim
  f_config_picom_config.ini:
    src: config/picom/config.ini
    dst: ~/.config/picom/config.ini
  f_config_polybar_modules_custom_pulseaudio-control.ini:
    src: config/polybar/modules/custom/pulseaudio-control.ini
    dst: ~/.config/polybar/modules/custom/pulseaudio-control.ini
  f_config_polybar_modules_battery.ini:
    src: config/polybar/modules/battery.ini
    dst: ~/.config/polybar/modules/battery.ini
  f_config_polybar_modules_cpu.ini:
    src: config/polybar/modules/cpu.ini
    dst: ~/.config/polybar/modules/cpu.ini
  f_config_polybar_modules_date.ini:
    src: config/polybar/modules/date.ini
    dst: ~/.config/polybar/modules/date.ini
  f_config_polybar_modules_filesystem.ini:
    src: config/polybar/modules/filesystem.ini
    dst: ~/.config/polybar/modules/filesystem.ini
  f_config_polybar_modules_i3.ini:
    src: config/polybar/modules/i3.ini
    dst: ~/.config/polybar/modules/i3.ini
  f_config_polybar_modules_memory.ini:
    src: config/polybar/modules/memory.ini
    dst: ~/.config/polybar/modules/memory.ini
  f_config_polybar_modules_network.ini:
    src: config/polybar/modules/network.ini
    dst: ~/.config/polybar/modules/network.ini
  f_config_polybar_modules_pulseaudio.ini:
    src: config/polybar/modules/pulseaudio.ini
    dst: ~/.config/polybar/modules/pulseaudio.ini
  f_config_polybar_modules_temperature.ini:
    src: config/polybar/modules/temperature.ini
    dst: ~/.config/polybar/modules/temperature.ini
  f_config_polybar_modules_xkeyboard.ini:
    src: config/polybar/modules/xkeyboard.ini
    dst: ~/.config/polybar/modules/xkeyboard.ini
  f_config_polybar_modules_xwindow.ini:
    src: config/polybar/modules/xwindow.ini
    dst: ~/.config/polybar/modules/xwindow.ini
  f_config_polybar_scripts_pulseaudio-control.bash:
    src: config/polybar/scripts/pulseaudio-control.bash
    dst: ~/.config/polybar/scripts/pulseaudio-control.bash
    chmod: '744'
  f_config_polybar_colors.ini:
    src: config/polybar/colors.ini
    dst: ~/.config/polybar/colors.ini
  f_config_polybar_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
  f_config_polybar_launch.sh:
    src: config/polybar/launch.sh
    dst: ~/.config/polybar/launch.sh
    chmod: '744'
  f_config_ranger_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_config_ranger_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
  f_config_rofi_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_config_rofi_soundboard.rasi:
    src: config/rofi/soundboard.rasi
    dst: ~/.config/rofi/soundboard.rasi
  f_config_vifm_vifmrc:
    src: config/vifm/vifmrc
    dst: ~/.config/vifm/vifmrc
  f_vim_plugged_vim-code-dark_colors_codedark.vim:
    src: vim/plugged/vim-code-dark/colors/codedark.vim
    dst: ~/.vim/plugged/vim-code-dark/colors/codedark.vim
  f_config_i3_scripts_monitor_setup_screen.sh:
    src: config/i3/scripts/monitor/setup_screen.sh
    dst: ~/.config/i3/scripts/monitor/setup_screen.sh
    chmod: '744'
  f_config_i3_scripts_monitor_reload_screen_setup.sh:
    src: config/i3/scripts/monitor/reload_screen_setup.sh
    dst: ~/.config/i3/scripts/monitor/reload_screen_setup.sh
    chmod: '744'
  f_config_i3_scripts_monitor_export_monitor_name_to_file.sh:
    src: config/i3/scripts/monitor/export_monitor_name_to_file.sh
    dst: ~/.config/i3/scripts/monitor/export_monitor_name_to_file.sh
    chmod: '744'
  f_config_zsh_zshenv:
    src: config/zsh/.zshenv
    dst: ~/.config/zsh/.zshenv
  f_config_i3_scripts_egnime_notif_answer.sh:
    src: config/i3/scripts/egnime_notif_answer.sh
    dst: ~/.config/i3/scripts/egnime_notif_answer.sh
    chmod: '755'
  f_config_polybar_bars_main_top.ini:
    src: config/polybar/bars/main/top.ini
    dst: ~/.config/polybar/bars/main/top.ini
  f_config_polybar_bars_main_bottom.ini:
    src: config/polybar/bars/main/bottom.ini
    dst: ~/.config/polybar/bars/main/bottom.ini
  f_config_polybar_bars_secondary_top.ini:
    src: config/polybar/bars/secondary/top.ini
    dst: ~/.config/polybar/bars/secondary/top.ini
  f_config_polybar_bars_tertiary_top.ini:
    src: config/polybar/bars/tertiary/top.ini
    dst: ~/.config/polybar/bars/tertiary/top.ini
profiles:
  Krapaince-MASTER-arch:
    variables:
      wallpaper: ~/.config/i3/wallpapers/Krapaince-MASTER/avatar.png
      picom-blur-method: gaussian
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_wallpapers_krapaince-master_avatar.png
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_reload_screen_setup.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_zsh_zshenv
    - f_config_polybar_bars_tertiary_top.ini
  Krapaince-arch:
    variables:
      wallpaper: ~/.config/i3/wallpapers/Krapaince/avatar.png
      picom-blur-method: dual_kawase
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_scripts_soundboard.sh
    - f_config_i3_wallpapers_krapaince_avatar.png
    - f_config_rofi_soundboard.rasi
    - f_config_i3_scripts_egnime_notif_answer.sh
  krapaince_tty:
    dotfiles:
    - f_zshrc
    - f_zsh_alias
    - f_clang-format_c
    - f_clang-format_cpp
    - f_clang-tidy
    - f_config_nvim_coc_snippets_c.json
    - f_config_nvim_coc_snippets_cpp.json
    - f_config_nvim_general_settings.vim
    - f_config_nvim_keys_mappings.vim
    - f_config_nvim_lua_plug-colorizer.lua
    - f_config_nvim_plug-config_airline.vim
    - f_config_nvim_plug-config_coc.vim
    - f_config_nvim_plug-config_fzf.vim
    - f_config_nvim_plug-config_git-messenger.vim
    - f_config_nvim_plug-config_markdown-preview.vim
    - f_config_nvim_plug-config_nerdtree.vim
    - f_config_nvim_plug-config_rnvimr.vim
    - f_config_nvim_plug-config_vim-clang-format.vim
    - f_config_nvim_plug-config_vim-commentary.vim
    - f_config_nvim_plug-config_vim-cpp-enhanced-highlight.vim
    - f_config_nvim_plug-config_vim-illuminate.vim
    - f_config_nvim_plug-config_vista.vim
    - f_config_nvim_vim-plug_plugins.vim
    - f_config_nvim_coc-settings.json
    - f_config_nvim_github-markdown.css
    - f_config_nvim_init.vim
    - f_config_nvim_snippet.vim
    - f_config_picom_config.ini
    - f_config_ranger_rc.conf
    - f_config_ranger_rifle.conf
    - f_vim_plugged_vim-code-dark_colors_codedark.vim
  krapaince_gui:
    dotfiles:
    - f_ideavimrc
    - f_config_dunst_dunstrc
    - f_config_dunst_reload.sh
    - f_config_i3_config
    - f_config_i3_scripts_keyboard_switcher.sh
    - f_config_i3_scripts_lock.sh
    - f_config_i3_scripts_set_wallpaper.sh
    - f_config_i3_scripts_suspend.sh
    - f_config_kitty_kitty.conf
    - f_config_polybar_bars_main_top.ini
    - f_config_polybar_bars_main_bottom.ini
    - f_config_polybar_bars_secondary_top.ini
    - f_config_polybar_modules_custom_pulseaudio-control.ini
    - f_config_polybar_modules_battery.ini
    - f_config_polybar_modules_cpu.ini
    - f_config_polybar_modules_date.ini
    - f_config_polybar_modules_filesystem.ini
    - f_config_polybar_modules_i3.ini
    - f_config_polybar_modules_memory.ini
    - f_config_polybar_modules_network.ini
    - f_config_polybar_modules_pulseaudio.ini
    - f_config_polybar_modules_temperature.ini
    - f_config_polybar_modules_xkeyboard.ini
    - f_config_polybar_modules_xwindow.ini
    - f_config_polybar_scripts_pulseaudio-control.bash
    - f_config_polybar_colors.ini
    - f_config_polybar_config.ini
    - f_config_polybar_launch.sh
    - f_config_rofi_config.rasi
    - f_config_vifm_vifmrc
