config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: nolink
  link_on_import: nolink
  keepdot: false
  longkey: true
dotfiles:
profiles:

  Krapaince-MASTER-arch:
    variables:
      dunst_monitor: 2

      i3lock_screen_number: 2

      MON_DP: DP2
      MON_HDMI: HDMI-0
      MON_DVI: DVI-D-0

      wallpaper_url: https://www.dropbox.com/s/2s2uu988vrgxzmc/Krapaince-MASTER-arch-reverse.png

      # Waybar / polybar network interfaces
      wired_network_interface: enp5s0
      wireless_network_interface: wlp3s0
    include:
    - krapaince_tty
    - krapaince_gui
    - krapaince_gui_x
    dotfiles:
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_reload_screen_setup.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_i3_env_env.sh

  Krapaince-arch:
    variables:
      wallpaper_url: https://www.dropbox.com/s/i2r7wsjbdxzer0h/wallpapers.zip?dl=1
      # Name of json containing monitor name & wallpaper path
      wallpaper_monitors: 'monitors-krapaince-arch'

      # Waybar / polybar network interfaces
      wired_network_interface: enp0s31f6
      wireless_network_interface: wlp3s0

      is_wayland: true
    include:
    - krapaince_tty
    - krapaince_gui
    - krapaince_gui_wayland

  krapaince-arch-x:
    dotfiles:
    - f_xinitrc

  krapaince_min:
    dotfiles:
      - f_config_omf_alias.fish
      - f_config_omf_bundle
      - f_config_omf_channel
      - f_config_omf_theme
      - f_config_omf_init.fish
      - f_config_nvim_init_krapaince_min.lua
      - f_config_nvim_lazy-lock.json
      - f_config_nvim_user

  krapaince_tty:
    dotfiles:
    - f_config_omf_alias.fish
    - f_config_omf_bundle
    - f_config_omf_channel
    - f_config_omf_theme
    - f_config_omf_init.fish
    - f_clang-format
    - f_clang-tidy
    - f_config_gitui_key_bindings.ron
    - f_iex_exs
    - npm_setup_action
    - f_config_nvim_ftplugin_markdown.vim
    - f_config_nvim_init.lua
    - f_config_nvim_lazy-lock.json
    - f_config_nvim_snippets
    - f_config_nvim_user
    - f_config_nvim_user_plugins_lsp
    - f_config_vifm_vifmrc
    - f_config_yazi
    - f_config_yt-dlp_config
    - f_gitconfig
    - f_gitconfig-epitech
    - f_gnupg_gpg-agent.conf
    - f_ignore
    - f_rustfmt.toml
    - f_stylua.toml

  krapaince_gui:
    dotfiles:
    - f_config_gtk-3.0_settings.ini
    - f_config_gtk-4.0_settings.ini
    - f_config_kitty
    - f_config_wezterm
    - f_config_kvantum_kvantum.kvconfig
    - f_config_pipewire_media-session.d_bluez-monitor.conf
    - f_config_rofi
    - f_config_wallpaper_color_set.json
    - f_config_zathura_zathurarc
    - f_ideavimrc
    - f_local_bin_colorbalance2
    - f_local_bin_wallpaper.py

  krapaince_gui_x:
    dotfiles:
    - f_config_dunst_dunstrc
    - f_config_i3_config
    - f_config_i3_scripts_keyboard_switcher.sh
    - f_config_i3_scripts_lock.sh
    - f_config_i3_scripts_suspend.sh

    - f_config_polybar_bars.ini
    - f_config_polybar_modules_custom_media.ini
    - f_config_polybar_modules_custom_pipewire-control.ini
    - f_config_polybar_modules_custom_temperature-cpu.ini
    - f_config_polybar_modules_custom_temperature-gpu.ini
    - f_config_polybar_modules_cpu.ini
    - f_config_polybar_modules_date.ini
    - f_config_polybar_modules_filesystem.ini
    - f_config_polybar_modules_i3.ini
    - f_config_polybar_modules_memory.ini
    - f_config_polybar_modules_network.ini
    - f_config_polybar_modules_xkeyboard.ini
    - f_config_polybar_modules_xwindow.ini
    - f_config_polybar_scripts_pipewire-control.bash
    - f_config_polybar_scripts_temperature-cpu.sh
    - f_config_polybar_scripts_temperature-gpu.sh
    - f_config_polybar_colors.ini
    - f_config_polybar_config.ini
    - f_config_polybar_launch.sh

    - f_config_picom_config.ini

    - f_xprofile
  krapaince_gui_wayland:
    dotfiles:
    - f_config_gammaconfig_config.ini

    - f_config_hypr

    - f_config_wallpaper_monitors.json

    - f_config_waybar

    - f_local_bin_change-sink.sh
    - f_local_bin_import-gsettings.sh
    - f_local_bin_colorbalance2
    - f_local_bin_screenrecord.sh
    - f_config_swaync_config.json
    - f_local_bin_temperature-cpu.sh
