config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: nolink
  link_on_import: nolink
  keepdot: false
  longkey: true
dotfiles:
profiles:

  Krapaince-MASTER-arch:
    variables:
      dunst_monitor: 2

      i3lock_screen_number: 2

      MON_DP: DP2
      MON_HDMI: HDMI-0
      MON_DVI: DVI-D-0

      wallpaper_url: https://www.dropbox.com/s/2s2uu988vrgxzmc/Krapaince-MASTER-arch-reverse.png

      # Waybar / polybar network interfaces
      wired_network_interface: enp5s0
      wireless_network_interface: wlp3s0
    include:
    - krapaince_tty
    - krapaince_gui
    - krapaince_gui_x
    dotfiles:
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_reload_screen_setup.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_i3_env_env.sh

  Krapaince-arch:
    variables:
      wallpaper_url: https://www.dropbox.com/s/zm48ldtbubrc5s0/Krapaince-arch.png
      # Name of json containing monitor name & wallpaper path
      wallpaper_monitors: 'monitors-krapaince-arch'

      # Waybar / polybar network interfaces
      wired_network_interface: enp0s31f6
      wireless_network_interface: wlp3s0

      is_wayland: true
    include:
    - krapaince_tty
    - krapaince_gui
    - krapaince_gui_wayland

  krapaince-arch-x:
    dotfiles:
    - f_xinitrc

  krapaince_min:
    dotfiles:
      - f_config_omf_alias.fish
      - f_config_omf_bundle
      - f_config_omf_channel
      - f_config_omf_theme
      - f_config_omf_init.fish
      - f_config_nvim_lua_plugins_comment.lua
      - f_config_nvim_lua_plugins_lualine.lua
      - f_config_nvim_lua_plugins_neo-tree.lua
      - f_config_nvim_lua_plugins_tabline.lua
      - f_config_nvim_lua_plugins_treesitter.lua
      - f_config_nvim_lua_plugins_vim-better-whitespace.lua
      - f_config_nvim_lua_plugins_vscode.lua
      - f_config_nvim_lua_highlights.lua
      - f_config_nvim_lua_mappings.lua
      - f_config_nvim_lua_options.lua
      - f_config_nvim_lua_plugins.lua
      - f_config_nvim_lua_utils.lua
      - f_config_nvim_init_krapaince_min.lua

  krapaince_tty:
    dotfiles:
    - f_config_omf_alias.fish
    - f_config_omf_bundle
    - f_config_omf_channel
    - f_config_omf_theme
    - f_config_omf_init.fish
    - f_clang-format_c
    - f_clang-format_cpp
    - f_clang-tidy
    - f_config_gitui_key_bindings.ron
    - f_iex_exs
    - npm_setup_action
    - f_config_nvim_ftplugin_markdown.vim
    - f_config_nvim_lua_plugins_lspconfig_clangd.lua
    - f_config_nvim_lua_plugins_lspconfig_elixirls.lua
    - f_config_nvim_lua_plugins_lspconfig_eslint.lua
    - f_config_nvim_lua_plugins_lspconfig_jsonls.lua
    - f_config_nvim_lua_plugins_lspconfig_init.lua
    - f_config_nvim_lua_plugins_lspconfig_null-ls.lua
    - f_config_nvim_lua_plugins_lspconfig_rust-analyzer.lua
    - f_config_nvim_lua_plugins_lspconfig_sumneko_lua.lua
    - f_config_nvim_lua_plugins_lspconfig_texlab.lua
    - f_config_nvim_lua_plugins_lspconfig_tsserver.lua
    - f_config_nvim_lua_plugins_lspconfig_utils.lua
    - f_config_nvim_lua_plugins_lspconfig_volar.lua
    - f_config_nvim_lua_plugins_comment.lua
    - f_config_nvim_lua_plugins_lualine.lua
    - f_config_nvim_lua_plugins_neo-tree.lua
    - f_config_nvim_lua_plugins_nvim-colorizer.lua
    - f_config_nvim_lua_plugins_nvim-ufo.lua
    - f_config_nvim_lua_plugins_symbols-outline.lua
    - f_config_nvim_lua_plugins_tabline.lua
    - f_config_nvim_lua_plugins_telescope.lua
    - f_config_nvim_lua_plugins_todo-comments.lua
    - f_config_nvim_lua_plugins_treesitter.lua
    - f_config_nvim_lua_plugins_vim-better-whitespace.lua
    - f_config_nvim_lua_plugins_vscode.lua
    - f_config_nvim_lua_plugins_vsnip.lua
    - f_config_nvim_lua_plugins_cmp.lua
    - f_config_nvim_lua_plugins_fidget.lua
    - f_config_nvim_lua_plugins_gitsigns.lua
    - f_config_nvim_lua_plugins_lsp-trouble.lua
    - f_config_nvim_lua_highlights.lua
    - f_config_nvim_lua_mappings.lua
    - f_config_nvim_lua_options.lua
    - f_config_nvim_lua_plugins.lua
    - f_config_nvim_lua_utils.lua
    - f_config_nvim_snippets_c.json
    - f_config_nvim_snippets_cpp.json
    - f_config_nvim_snippets_python.json
    - f_config_nvim_snippets_yaml.json
    - f_config_nvim_init.lua
    - f_config_ranger_rc.conf
    - f_config_ranger_rifle.conf
    - f_config_vifm_vifmrc
    - f_config_yt-dlp_config
    - f_gitconfig
    - f_gitconfig-epitech
    - f_gnupg_gpg-agent.conf
    - f_ignore
    - f_local_bin_pinentry.sh
    - f_rustfmt.toml
    - f_stylua.toml

  krapaince_gui:
    dotfiles:
    - f_config_dunst_dunstrc
    - f_config_gtk-3.0_settings.ini
    - f_config_gtk-4.0_settings.ini
    - f_config_kitty_kitty.conf
    - f_config_kvantum_kvantum.kvconfig
    - f_config_pipewire_media-session.d_bluez-monitor.conf
    - f_config_wallpaper_color_set.json
    - f_config_zathura_zathurarc
    - f_ideavimrc
    - f_local_bin_colorbalance2
    - f_local_bin_wallpaper.py

  krapaince_gui_x:
    dotfiles:
    - f_config_i3_config
    - f_config_i3_scripts_keyboard_switcher.sh
    - f_config_i3_scripts_lock.sh
    - f_config_i3_scripts_suspend.sh

    - f_config_polybar_bars.ini
    - f_config_polybar_modules_custom_media.ini
    - f_config_polybar_modules_custom_pipewire-control.ini
    - f_config_polybar_modules_custom_temperature-cpu.ini
    - f_config_polybar_modules_custom_temperature-gpu.ini
    - f_config_polybar_modules_cpu.ini
    - f_config_polybar_modules_date.ini
    - f_config_polybar_modules_filesystem.ini
    - f_config_polybar_modules_i3.ini
    - f_config_polybar_modules_memory.ini
    - f_config_polybar_modules_network.ini
    - f_config_polybar_modules_xkeyboard.ini
    - f_config_polybar_modules_xwindow.ini
    - f_config_polybar_scripts_pipewire-control.bash
    - f_config_polybar_scripts_temperature-cpu.sh
    - f_config_polybar_scripts_temperature-gpu.sh
    - f_config_polybar_colors.ini
    - f_config_polybar_config.ini
    - f_config_polybar_launch.sh

    - f_config_rofi_config.rasi

    - f_config_picom_config.ini

    - f_xprofile
  krapaince_gui_wayland:
    dotfiles:
    - f_config_gammaconfig_config.ini

    - f_config_sway_bindings
    - f_config_sway_config
    - f_config_sway_workspace

    - f_config_sway_scripts_lock.sh
    - f_config_sway_script_pipewire-control.bash

    - f_config_wallpaper_monitors.json

    - f_config_waybar_styles_battery.css
    - f_config_waybar_styles_color.css
    - f_config_waybar_styles_cpu.css
    - f_config_waybar_styles_memory.css
    - f_config_waybar_styles_workspaces.css
    - f_config_waybar_config.json
    - f_config_waybar_style.css

    - f_config_wofi_config
    - f_config_wofi_style.css

    - f_local_bin_change-sink.sh
    - f_local_bin_import-gsettings.sh
    - f_local_bin_colorbalance2
    - f_local_bin_sway
    - f_local_bin_temperature-cpu.sh
