config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: nolink
  link_on_import: nolink
  keepdot: false
  longkey: true
dotfiles:
profiles:

  Krapaince-MASTER-arch:
    variables:
      wallpaper_url: https://www.dropbox.com/s/a4u245cd1gc56ji/Krapaince-MASTER-arch.png
      polybar_wired_network_interface: enp5s0
      polybar_wireless_network_interface: wlp3s0
      kitty_font: CaskaydiaCove Nerd Font Book
      i3lock_screen_number: 2
      dunst_monitor: 2
      dunst_geometry: "300x10+20+40"
      monitor_01: DVI-D-0
      monitor_02: HDMI-0
      monitor_03: DP-1-5
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_reload_screen_setup.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_i3_env_env.sh

  Krapaince-arch:
    variables:
      wallpaper_url: https://www.dropbox.com/s/zm48ldtbubrc5s0/Krapaince-arch.png
      picom_blur_method: dual_kawase
      polybar_wired_network_interface: enp0s31f6
      polybar_wireless_network_interface: wlp3s0
      kitty_font: CaskaydiaCove Nerd Font Book
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_scripts_soundboard.sh
    - f_config_rofi_soundboard.rasi
    - f_config_i3_scripts_egnime_notif_answer.sh
    - f_xinitrc

  krapaince_min:
    dotfiles:
      - f_config_omf_alias.fish
      - f_config_omf_bundle
      - f_config_omf_channel
      - f_config_omf_theme
      - f_config_omf_init.fish
      - f_config_nvim_lua_config_lualine.lua
      - f_config_nvim_lua_config_nvim-tree.lua
      - f_config_nvim_lua_config_treesitter.lua
      - f_config_nvim_lua_config_vim_commentary.lua
      - f_config_nvim_lua_config.lua
      - f_config_nvim_lua_highlights.lua
      - f_config_nvim_lua_mappings.lua
      - f_config_nvim_lua_options.lua
      - f_config_nvim_lua_plugins.lua
      - f_config_nvim_lua_utils.lua
      - f_config_nvim_init_krapaince_min.vim
      - f_config_nvim_lua_config_treesitter.lua

  krapaince_tty:
    dotfiles:
    - f_config_omf_alias.fish
    - f_config_omf_bundle
    - f_config_omf_channel
    - f_config_omf_theme
    - f_config_omf_init.fish
    - f_clang-format_c
    - f_clang-format_cpp
    - f_clang-tidy
    - f_config_gitui_key_config.ron
    - f_config_nvim_ftplugin_markdown.vim
    - f_config_nvim_lua_config_lsp_clangd.lua
    - f_config_nvim_lua_config_lsp_init.lua
    - f_config_nvim_lua_config_lsp_rust-analyzer.lua
    - f_config_nvim_lua_config_lsp_sumneko_lua.lua
    - f_config_nvim_lua_config_lsp_texlab.lua
    - f_config_nvim_lua_config_animate.lua
    - f_config_nvim_lua_config_lualine.lua
    - f_config_nvim_lua_config_nvim-colorizer.lua
    - f_config_nvim_lua_config_nvim-tree.lua
    - f_config_nvim_lua_config_telescope.lua
    - f_config_nvim_lua_config_todo-comments.lua
    - f_config_nvim_lua_config_treesitter.lua
    - f_config_nvim_lua_config_vim_commentary.lua
    - f_config_nvim_lua_config_vista.lua
    - f_config_nvim_lua_config_vsnip.lua
    - f_config_nvim_lua_config_compe.lua
    - f_config_nvim_lua_config_git-messenger.lua
    - f_config_nvim_lua_config_lsp-trouble.lua
    - f_config_nvim_lua_config.lua
    - f_config_nvim_lua_highlights.lua
    - f_config_nvim_lua_mappings.lua
    - f_config_nvim_lua_options.lua
    - f_config_nvim_lua_plugins.lua
    - f_config_nvim_lua_utils.lua
    - f_config_nvim_snippets_c.json
    - f_config_nvim_snippets_yaml.json
    - f_config_nvim_snippets_cpp.json
    - f_config_nvim_init.vim
    - f_config_ranger_rc.conf
    - f_config_ranger_rifle.conf
    - f_config_vifm_vifmrc
    - f_ignore
    - f_gitconfig

  krapaince_gui:
    dotfiles:
    - f_ideavimrc
    - f_config_dunst_dunstrc
    - f_config_dunst_reload.sh
    - f_config_i3_config
    - f_config_i3_scripts_keyboard_switcher.sh
    - f_config_i3_scripts_lock.sh
    - f_config_i3_scripts_set_wallpaper.sh
    - f_config_i3_scripts_suspend.sh
    - f_config_kitty_kitty.conf
    - f_config_polybar_bars.ini
    - f_config_polybar_modules_custom_pulseaudio-control.ini
    - f_config_polybar_modules_custom_temperature-cpu.ini
    - f_config_polybar_modules_custom_temperature-gpu.ini
    - f_config_polybar_modules_battery.ini
    - f_config_polybar_modules_cpu.ini
    - f_config_polybar_modules_date.ini
    - f_config_polybar_modules_filesystem.ini
    - f_config_polybar_modules_i3.ini
    - f_config_polybar_modules_memory.ini
    - f_config_polybar_modules_network.ini
    - f_config_polybar_modules_pulseaudio.ini
    - f_config_polybar_modules_xkeyboard.ini
    - f_config_polybar_modules_xwindow.ini
    - f_config_polybar_scripts_pulseaudio-control.bash
    - f_config_polybar_scripts_temperature-cpu.sh
    - f_config_polybar_scripts_temperature-gpu.sh
    - f_config_polybar_colors.ini
    - f_config_polybar_config.ini
    - f_config_polybar_launch.sh
    - f_config_rofi_config.rasi
    - f_config_zathura_zathurarc
    - f_config_picom_config.ini
    - f_config_kvantum_kvantum.kvconfig
    - f_xprofile
