config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: nolink
  link_on_import: nolink
  keepdot: false
  longkey: true
dotfiles:
profiles:
  Krapaince-MASTER-arch:
    variables:
      wallpaper: ~/.config/i3/wallpapers/Krapaince-MASTER/avatar.png
      polybar_wired_network_interface: enp5s0
      kitty_font: CaskaydiaCove Nerd Font Book
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_wallpapers_krapaince-master_avatar.png
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_reload_screen_setup.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_zsh_zshenv
  Krapaince-arch:
    variables:
      wallpaper: ~/.config/i3/wallpapers/Krapaince/avatar.png
      picom_blur_method: dual_kawase
      polybar_wired_network_interface: enp0s31f6
      polybar_wireless_network_interface: wlp3s0
      kitty_font: CaskaydiaCove Nerd Font Book
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_scripts_soundboard.sh
    - f_config_i3_wallpapers_krapaince_avatar.png
    - f_config_rofi_soundboard.rasi
    - f_config_i3_scripts_egnime_notif_answer.sh
    - f_xinitrc
  Krapaince-ubuntu:
    variables:
      wallpaper: ~/.config/i3/wallpapers/Krapaince-ubuntu/avatar.png
      picom_blur_method: gaussian
      polybar_wired_network_interface: enp1s0
      git_name: Mathieu Pointecouteau
      git_email: m.pointecouteau@alcom-tech.com
      kitty_font: Caskaydia Cove Nerd Font Complete
    include:
    - krapaince_tty
    - krapaince_gui
    dotfiles:
    - f_config_i3_wallpapers_krapaince-ubuntu_avatar.png
    - f_config_i3_scripts_monitor_setup_screen.sh
    - f_config_i3_scripts_monitor_export_monitor_name_to_file.sh
    - f_config_zsh_zshenv
  krapaince_tty:
    dotfiles:
    - f_zshrc
    - f_zsh_alias
    - f_clang-format_c
    - f_clang-format_cpp
    - f_clang-tidy
    - f_config_gitui_key_config.ron
    - f_config_nvim_lua_config_lsp_clangd.lua
    - f_config_nvim_lua_config_lsp_init.lua
    - f_config_nvim_lua_config_lsp_rust-analyzer.lua
    - f_config_nvim_lua_config_lsp_sumneko_lua.lua
    - f_config_nvim_lua_config_lsp_texlab.lua
    - f_config_nvim_lua_config_animate.lua
    - f_config_nvim_lua_config_lualine.lua
    - f_config_nvim_lua_config_nvim-colorizer.lua
    - f_config_nvim_lua_config_nvim-tree.lua
    - f_config_nvim_lua_config_telescope.lua
    - f_config_nvim_lua_config_treesitter.lua
    - f_config_nvim_lua_config_vim_commentary.lua
    - f_config_nvim_lua_config_vsnip.lua
    - f_config_nvim_lua_config_compe.lua
    - f_config_nvim_lua_config_git-messenger.lua
    - f_config_nvim_lua_config_lsp-trouble.lua
    - f_config_nvim_lua_config.lua
    - f_config_nvim_lua_highlights.lua
    - f_config_nvim_lua_mappings.lua
    - f_config_nvim_lua_plugins.lua
    - f_config_nvim_lua_utils.lua
    - f_config_nvim_snippets_c.json
    - f_config_nvim_snippets_cpp.json
    - f_config_nvim_vim_plugin.vim
    - f_config_nvim_init.vim
    - f_config_nvim_settings.vim
    - f_config_ranger_rc.conf
    - f_config_ranger_rifle.conf
    - f_config_vifm_vifmrc
    - f_ignore
    - f_gitconfig
  krapaince_gui:
    dotfiles:
    - f_ideavimrc
    - f_config_dunst_dunstrc
    - f_config_dunst_reload.sh
    - f_config_i3_config
    - f_config_i3_scripts_keyboard_switcher.sh
    - f_config_i3_scripts_lock.sh
    - f_config_i3_scripts_set_wallpaper.sh
    - f_config_i3_scripts_suspend.sh
    - f_config_kitty_kitty.conf
    - f_config_polybar_bars.ini
    - f_config_polybar_modules_custom_pulseaudio-control.ini
    - f_config_polybar_modules_battery.ini
    - f_config_polybar_modules_cpu.ini
    - f_config_polybar_modules_date.ini
    - f_config_polybar_modules_filesystem.ini
    - f_config_polybar_modules_i3.ini
    - f_config_polybar_modules_memory.ini
    - f_config_polybar_modules_network.ini
    - f_config_polybar_modules_pulseaudio.ini
    - f_config_polybar_modules_temperature.ini
    - f_config_polybar_modules_xkeyboard.ini
    - f_config_polybar_modules_xwindow.ini
    - f_config_polybar_scripts_pulseaudio-control.bash
    - f_config_polybar_colors.ini
    - f_config_polybar_config.ini
    - f_config_polybar_launch.sh
    - f_config_rofi_config.rasi
    - f_config_zathura_zathurarc
    - f_config_picom_config.ini
    - f_config_kvantum_kvantum.kvconfig
    - f_xprofile
