width = 250
height = 640

force_window = false

font = "/usr/share/fonts/TTF/iosevka-regular.ttc"
font_size = 13

bg_color = 0x282C33FF
font_color = 0x8ca0aaff

term = "wezterm"

[input_text]
bg_color = 0x282C33ff
font_color = 0xffffffff

margin = "12"
padding = "1.7 -4"

[list_items]
font_color = 0xf8f8f2ff

selected_font_color = 0xec7875ff
match_color = 0xec7875ff

margin = "12"

hide_actions = true

item_spacing = 25
icon_spacing = 12

[icon]
size = 16
theme = "Fluent-orange-dark"
fallback_icon_path = "/usr/share/icons/Adwaita/16x16/categories/applications-engineering-symbolic.symbolic.png"
